# Generated by Django 3.1.1 on 2020-09-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lecture", "0003_auto_20200916_1506"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="class",
            name="class_id",
        ),
        migrations.AlterField(
            model_name="class",
            name="end_dt",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="class",
            name="start_dt",
            field=models.DateField(),
        ),
    ]
