# Generated by Django 3.1.1 on 2020-09-21 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employment", "0003_auto_20200918_1110"),
        ("payment", "0004_auto_20200921_1158"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="emp_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="employment.employment"
            ),
        ),
    ]
