# Generated by Django 3.1.1 on 2020-09-18 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
        ("employment", "0002_employment_emp_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employment",
            name="emp_status",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="employment",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employments",
                to="user.user",
            ),
        ),
    ]
