# Generated by Django 3.1.1 on 2020-09-15 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lecture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nm', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=60)),
                ('class_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lecture.class')),
            ],
        ),
    ]
